// test all

require('./add-eigyobi');
require('./add');
require('./check-day-info-holiday');
require('./count-eigyobi');
require('./diff-seconds');
require('./diff-days');
require('./diff-minutes');
require('./end-class');
require('./end-instance');
require('./events');
require('./format-nendo');
require('./get-cal-data');
require('./get-date-array');
require('./get-day-info');
require('./get-holiday-name');
require('./get-holidays');
require('./get-nengo');
require('./get-week-index');
require('./get-week-number-class');
require('./get-week-number-instance');
require('./is-holiday-closed');
require('./is-opened');
require('./is-regular-holiday');
require('./is-season-holiday');
require('./pass-eigyobi');
require('./pass-nendo-eigyobi');
require('./remain-eigyobi');
require('./remain-nendo-eigyobi');
require('./separate');
require('./start-class');
require('./start-instance');
require('./suji');
require('./to-date');
require('./to-eigyobi');
require('./xday');

require('./format/all.js');